ec-th2012-c/ec-th2012-c/Controllers/ManagePartnerBuySideController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ec_th2012_c.DAO;
using System.Net;
using ec_th2012_c.Models;


namespace ec_th2012_c.Controllers
{
    [Authorize(Roles="Admin")]
    public class ManagePartnerBuySideController : Controller
    {
        private PartnerBuySideDAO db = new PartnerBuySideDAO();
        private EC_DBEntities dbEntities = new EC_DBEntities();
        // GET: ManagePartnerBuySide
        public ActionResult Index()
        {
            var listPartner = db.getListPartner();
            return View(listPartner);
        }

      
        public ActionResult Active(string id)
        {
            db.changeActivePartner(id);
            return RedirectToAction("Index");
        }



        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var partner = db.findPartner(id);
            if (partner == null)
            {
                return HttpNotFound();
            }
            
            ViewBag.ReturnUrl = System.Web.HttpContext.Current.Request.UrlReferrer;
            return View(partner);
        }

        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var partner = db.findPartner(id);
            if (partner == null)
            {
                return HttpNotFound();
            }
            ViewBag.ReturnUrl = System.Web.HttpContext.Current.Request.UrlReferrer;
            return View(partner);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PARTNER_INFO_BUYSIDE model)
        {
            if (ModelState.IsValid)
            {
                db.editPartner(model);

                return RedirectToAction("Details/"+model.ID);
            }

            return View(model);

        }

        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var partner = db.findPartner(id);
            if (partner == null)
            {
                return HttpNotFound();
            }
            db.deletePartner(id);
            return RedirectToAction("Index");
        }

        public ActionResult Contracts(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var partner = db.findPartner(id);
            if (partner == null)
            {
                return HttpNotFound();
            }
            var listContracts = partner.AspNetUsers.CONTRACT_BUYSIDE.ToList();
            List<String> listResult = new List<String>();
            foreach (var item in listContracts)
            {
                listResult.Add("Đang hợp tác");
            }
            ViewData["listResults"] = listResult;
            return View("Contracts", listContracts);
        }

        public ActionResult DetailContract(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CONTRACT_BUYSIDE contract_buyside = dbEntities.CONTRACT_BUYSIDE.Find(id);
            if (contract_buyside == null)
            {
                return HttpNotFound();
            }
            return View(contract_buyside);
        }
    }
}

ec-th2012-c/ec-th2012-c/Views/ManagePartnerBuySide/Contracts.cshtml
@model IEnumerable<ec_th2012_c.Models.CONTRACT_BUYSIDE>
@using ec_th2012_c.Models
@{
    ViewBag.Title = "Contracts";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}




<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon white user"></i><span class="break"></span>THÔNG TIN KÝ KẾT HỢP ĐỒNG</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        <th>Tên sản phẩm</th>
                        <th>Hình ảnh</th>
                        <th>Thời hạn hợp đồng</th>
                        <th>Tình trạng</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        List<String> listResult = (List<String>)ViewData["listResults"];
                        List<CONTRACT_BUYSIDE> listContractPartner = (List<CONTRACT_BUYSIDE>)Model;
                        for (int i = 0; i < listContractPartner.Count; i++)
                        {
                            <tr>
                                <td>@Html.DisplayFor(model => listContractPartner[i].PRODUCTS.NAME)</td>
                                <td class="center">
                                    <img src="@listContractPartner[i].PRODUCTS.IMG" class="imgcus" />
                                </td>
                                <td class="center">@Html.DisplayFor(model => listContractPartner[i].COOPTIME)</td>
                                <td class="center">@listResult[i]</td>
                                <td class="center">
                                    @{
                            if (listResult[i].Equals("Ký kết thất bại")
                                || listResult[i].Equals("Đang chờ duyệt"))
                            {
                                <a class="btn btn-warning" href="@Url.Action("Details", "B2BBuySide", new { id = listContractPartner[i].ID })">
                                    <i class="halflings-icon white zoom-in"></i>
                                </a>
                                        <a class="btn btn-danger" href="@Url.Action("DeleteContractByPartner", "B2BBuySide", new { id = listContractPartner[i].ID })">
                                            <i class="halflings-icon white trash"></i>
                                        </a>
                            }
                            else
                            {
                                <a class="btn btn-warning" href="@Url.Action("Details", "B2BBuySide", new { id = listContractPartner[i].ID })">
                                    <i class="halflings-icon white zoom-in"></i>
                                </a>
                            }
                                    }
                                </td>
                            </tr>
                        }
                    }

                </tbody>
            </table>
        </div>
    </div><!--/span-->
</div>

ec-th2012-c/ec-th2012-c/Views/ManagePartnerBuySide/DetailContract.cshtml
@model ec_th2012_c.Models.CONTRACT_BUYSIDE
@{
    ViewBag.Title = "DetailContract";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}




<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon white edit"></i><span class="break"></span>Thông tin hợp đồng</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <form class="form-horizontal">
                <fieldset>
                    <div class="control-group control-imagedetail">
                        <br />
                        <label class="control-label-custom" for="focusedInput" style="text-align:center">
                            <img src="@Html.DisplayFor(model => model.PRODUCTS.IMG)" class="imdetail" />
                        </label>
                    </div>
                    <div class="control-group control-detail">
                        <div class="control-group">
                            <label class="control-label" for="focusedInput">Tên sản phẩm: </label>
                            <label class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.PRODUCTS.NAME)</label>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="focusedInput">Số lượng tồn kho tối thiểu: </label>
                            <label class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.MININVENTORY)</label>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="focusedInput">Số lượng cung cấp tối thiểu: </label>
                            <label class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.MINPROVIDE)</label>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="focusedInput">Thời gian giao hàng: </label>
                            <label class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.DELAYTIME)</label>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="focusedInput">Thời gian hợp tác: </label>
                            <label class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.COOPTIME)</label>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="focusedInput">Thời gian chuyển tiền: </label>
                            <label class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.BILLTIME)</label>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="focusedInput">Ngày bắt đầu: </label>
                            <label class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.STARTDAY)</label>
                        </div>
                        <div class="control-group">
                            <label class="control-label" for="focusedInput">Ngày kết thúc: </label>
                            <label class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.ENDDAY)</label>
                        </div>
                    </div>


                </fieldset>

            </form>

        </div>
    </div><!--/span-->

</div><!--/row-->
<div class="form-actions">
    <button type="submit" class="btn btn-primary" onclick="window.location.href='@Url.Action("Index", "B2BBuySide")'">Back</button>
</div>

ec-th2012-c/ec-th2012-c/Views/ManagePartnerBuySide/Details.cshtml
@model ec_th2012_c.Models.PARTNER_INFO_BUYSIDE

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon white edit"></i><span class="break"></span>Thông tin đối tác</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <form class="form-horizontal">
                <fieldset>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Tên đối tác: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.NAME)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Mô tả: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.DESCRIPTION)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Địa chỉ: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.AspNetUsers.ADDRESS)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Email: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.AspNetUsers.EMAIL)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Số điện thoại: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.AspNetUsers.PHONE)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Comsumer Key: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.CONSUMER_KEY)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Trạng thái: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.AspNetUsers.ACTIVE)</p>
                    </div>
                   
                   
                </fieldset>
            </form>

        </div>
    </div><!--/span-->

</div><!--/row-->



<div class="form-actions">
    <button type="submit" class="btn btn-primary" onclick="window.location.href='@Url.Action("Edit", "ManagePartnerBuySide", new { id = Model.ID })'">Edit</button>
    <button class="btn" onclick="window.location.href='@Url.Action("returnURL", "AdminHome", new { returnURL = ViewBag.ReturnUrl })'">Back</button>
</div>

ec-th2012-c/ec-th2012-c/Views/ManagePartnerBuySide/Edit.cshtml
@model ec_th2012_c.Models.PARTNER_INFO_BUYSIDE
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm())
{
    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="halflings-icon white edit"></i><span class="break"></span>Chỉnh sửa thông tin đối tác mua hàng</h2>
                <div class="box-icon">
                    <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                    <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                    <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
                </div>
            </div>
            <div class="box-content">

                @Html.AntiForgeryToken()
                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)
                    <fieldset>


                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Tên đối tác</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.NAME, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NAME, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Mô tả</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.DESCRIPTION, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DESCRIPTION, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Địa chỉ</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.AspNetUsers.ADDRESS, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.AspNetUsers.ADDRESS, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Email</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.AspNetUsers.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.AspNetUsers.EMAIL, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Số điện thoại</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.AspNetUsers.PHONE, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.AspNetUsers.PHONE, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Consumer Key</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.CONSUMER_KEY, new { htmlAttributes = new { @class = "form-control", @ReadOnly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.CONSUMER_KEY, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Trạng thái</label>
                            <div class="controls">
                                @Html.DropDownListFor(m => m.AspNetUsers.ACTIVE, Model.getActive(), null, new { @class = "form-control" })
                                
                                @Html.ValidationMessageFor(model => model.AspNetUsers.ACTIVE, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        



                    </fieldset>


                </div>

            </div>
        </div><!--/span-->

    </div><!--/row-->





    <div class="form-actions">
        <button type="submit" class="btn btn-primary">Save Change</button>
        <button class="btn" onclick="window.location.href='@Url.Action("returnURL", "AdminHome", new { returnURL = ViewBag.ReturnUrl })'">Cancel</button>
    </div>
}

ec-th2012-c/ec-th2012-c/Views/ManagePartnerBuySide/Index.cshtml
@model IEnumerable<ec_th2012_c.Models.PARTNER_INFO_BUYSIDE>

@{
    ViewBag.Title = "Quản lý đối tác bán hàng";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="header_create">
    <a class="btn btn-success" href="@Url.Action("Create", "ManagePartnerBuySide")">
        <i class="halflings-icon edit white"></i>
    </a>

</div>

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon white user"></i><span class="break"></span>Danh sách đối tác bán hàng</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        <th class="center_custom">Tên đối tác</th>
                        
                        <th class="center_custom">Email</th>
                        <th class="center_custom">Consumer_key</th>
                        <th class="center_custom">Tình trạng</th>
                        <th class="center_custom">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {

                        <tr>
                            <td>@Html.DisplayFor(m => item.NAME)</td>
                            <td class="center_custom">@Html.DisplayFor(m => item.AspNetUsers.EMAIL)</td>
                            <td class="center_custom">@Html.DisplayFor(m => item.CONSUMER_KEY)</td>
                            @{
                        if (item.AspNetUsers.ACTIVE == "Active")
                        {
                            <td class="center_custom">
                                <a class="label label-success" href="@Url.Action("Active", "ManagePartnerBuySide", new { id = item.ID })">
                                    Avtive
                                </a>
                            </td>

                        }
                        else
                        {
                            <td class="center_custom">
                                <a class="label label-warning" href="@Url.Action("Active", "ManagePartnerBuySide", new { id = item.ID })">
                                    Deactivate
                                </a>
                            </td>
                        }
}
                           

                            <td class="center_custom">

                                <a class="btn btn-success" href="@Url.Action("Details", "ManagePartnerBuySide", new { id = item.ID })">
                                    <i class="halflings-icon white zoom-in"></i>
                                </a>
                                <a class="btn btn-info" href="@Url.Action("Contracts", "ManagePartnerBuySide", new { id = item.ID })">
                                    <i class=" halflings-icon list white"></i>
                                </a>
                                <a class="btn btn-danger" href="@Url.Action("Delete", "ManagePartnerBuySide", new { id = item.ID })" onclick="return confirm('Do you want delete this partner?')">
                                    <i class="halflings-icon white trash"></i>
                                </a>
                            </td>
                        </tr>



                    }


                </tbody>
            </table>
        </div>
    </div><!--/span-->
</div>