ec-th2012-c/ec-th2012-c/Controllers/B2BSellSideController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ec_th2012_c.Models;
using ec_th2012_c.DAO;

namespace ec_th2012_c.Controllers
{
    [Authorize(Roles = "Admin")]
    public class B2BSellSideController : Controller
    {
        private ContractDAO db = new ContractDAO();

        //private EC_DBEntities db = new EC_DBEntities();

        // GET: B2BSellSide
        public ActionResult Index()
        {
            var listContract = db.getListContractSellSide();

            return View("Index", listContract);
        }

        //GET: B2BSellSide/Details/5
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CONTRACT_SELLSIDE cONTRACT_SELLSIDE = db.getContractSellSideByID(id);
            if (cONTRACT_SELLSIDE == null)
            {
                return HttpNotFound();
            }
            ViewBag.ReturnUrl = System.Web.HttpContext.Current.Request.UrlReferrer;
            return View(cONTRACT_SELLSIDE);
        }

        [HttpGet]
        public ActionResult startShipping(int id, int quantity, string date)
        {
            if (db.startShipping(id, quantity, date))
            {

                return Json("Chuyển hàng thành công", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("Chuyển hàng KHÔNG thành công. Vui lòng thử lại", JsonRequestBehavior.AllowGet);
            }


        }

        [HttpGet]
        public ActionResult listBillSellSide(int? id)
        {
            var listBill = db.getlistBillSellSide(id);
            ViewBag.ReturnUrl = System.Web.HttpContext.Current.Request.UrlReferrer;
            return View("listBill", listBill);
        }

        [HttpGet]
        public ActionResult shippingOk(int? idContract, int? idBill)
        {
            db.shippingOk(idBill);
            return RedirectToAction("listBillSellSide", new { id = idContract });
        }

        [HttpGet]
        public ActionResult shippingOkAllList(int? idBill)
        {
            db.shippingOk(idBill);
            return RedirectToAction("getAllListBill");
        }

        // GET: B2BSellSide/Create
        public ActionResult Create()
        {
            ViewBag.PARTNERID = db.selectListPartner(null);
            ViewBag.PRODUCTID = db.selectListProduct(null);
            ViewBag.ReturnUrl = System.Web.HttpContext.Current.Request.UrlReferrer;
            return View();
        }

        // POST: B2BSellSide/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CONTRACT_SELLSIDE cONTRACT_SELLSIDE)
        {

            db.createContractSellSide(cONTRACT_SELLSIDE);

            return RedirectToAction("Index");

        }

        // GET: B2BSellSide/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = db.getContractSellSideByID(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            ViewBag.ReturnUrl = System.Web.HttpContext.Current.Request.UrlReferrer;
            ViewBag.PARTNERID = db.selectListPartner(model.PARTNERID);
            ViewBag.PRODUCTID = db.selectListProduct(model.PRODUCTID);
            return View(model);
        }

        // POST: B2BSellSide/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CONTRACT_SELLSIDE cONTRACT_SELLSIDE)
        {
            if (ModelState.IsValid)
            {
                db.editContract(cONTRACT_SELLSIDE);

                return RedirectToAction("Details/" + cONTRACT_SELLSIDE.ID);
            }
            ViewBag.PARTNERID = db.selectListPartner(cONTRACT_SELLSIDE.PARTNERID);
            ViewBag.PRODUCTID = db.selectListProduct(cONTRACT_SELLSIDE.PRODUCTID);
            return View(cONTRACT_SELLSIDE);
        }

        // GET: B2BSellSide/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CONTRACT_SELLSIDE cONTRACT_SELLSIDE = db.getContractSellSideByID(id);
            if (cONTRACT_SELLSIDE == null)
            {
                return HttpNotFound();
            }
            db.deleteContractSellSide(id);
            return RedirectToAction("Index");
        }

        public ActionResult getAllListBill()
        {
            var listBill = db.getlistBillSellSide();
           
            return View(listBill);
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

ec-th2012-c/ec-th2012-c/Views/B2BSellSide/Create.cshtml
@model ec_th2012_c.Models.CONTRACT_SELLSIDE

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
@using (Html.BeginForm())
{
    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="halflings-icon white edit"></i><span class="break"></span>Chỉnh sửa hợp đồng</h2>
                <div class="box-icon">
                    <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                    <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                    <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
                </div>
            </div>
            <div class="box-content">

                @Html.AntiForgeryToken()
                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)
                    <fieldset>




                        <div class="control-group">
                            <label class="control-label" for="selectError">Tên đối tác</label>
                            <div class="controls">
                                @Html.DropDownList("PARTNERID", null, new { @data_rel = "chosen" })
                                @Html.ValidationMessageFor(model => model.PARTNERID, "", new { @class = "text-danger" })
                            </div>


                        </div>

                        <div class="control-group">
                            <label class="control-label" for="selectError">Tên sản phẩm</label>
                            <div class="controls">
                                @Html.DropDownList("PRODUCTID", null, new { @data_rel = "chosen" })
                                @Html.ValidationMessageFor(model => model.PRODUCTID, "", new { @class = "text-danger" })
                            </div>


                        </div>

                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Số lượng tồn kho tối thiểu</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.MININVENTORY, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.MININVENTORY, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Số lượng cung cấp tối thiểu</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.MINPROVIDE, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.MINPROVIDE, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Thời gian giao hàng</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.DELAYTIME, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DELAYTIME, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Thời gian hợp tác</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.COOPTIME, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.COOPTIME, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Thời gian chuyển tiền</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.BILLTIME, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.BILLTIME, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Ngày bắt đầu</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.STARTDAY, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.STARTDAY, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Ngày kết thúc</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.ENDDAY, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ENDDAY, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Trạng thái hợp đồng</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.ACTIVE, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ACTIVE, "", new { @class = "text-danger" })
                            </div>
                        </div>





                    </fieldset>


                </div>

            </div>
        </div><!--/span-->

    </div><!--/row-->


    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="halflings-icon white edit"></i><span class="break"></span>Chỉnh sửa thông tin khách hàng</h2>
                <div class="box-icon">
                    <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                    <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                    <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
                </div>
            </div>
            <div class="box-content">


                <div class="form-horizontal">


                    <fieldset>





                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Mã hợp đồng</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.ORDER_ID_PARTNER, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ORDER_ID_PARTNER, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Mã sản phẩm</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.PRODUC_ID_PARTNER, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PRODUC_ID_PARTNER, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Tên sản phẩm</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.PRODUCT_NAME_PARTNER, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PRODUCT_NAME_PARTNER, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Số lượng tồn kho</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.PRODUCT_QUANTITY_PARTNER, new { htmlAttributes = new { @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.PRODUCT_QUANTITY_PARTNER, "", new { @class = "text-danger"  })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Trạng thái</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.STATE, new { htmlAttributes = new { @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.STATE, "", new { @class = "text-danger" })
                            </div>
                        </div>





                    </fieldset>


                </div>

            </div>
        </div><!--/span-->

    </div><!--/row-->
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">Create</button>
        <button class="btn" onclick="window.location.href='@Url.Action("returnURL", "AdminHome", new { returnURL = ViewBag.ReturnUrl })'">Cancel</button>
    </div>
}

ec-th2012-c/ec-th2012-c/Views/B2BSellSide/Details.cshtml
@model ec_th2012_c.Models.CONTRACT_SELLSIDE

@{
    ViewBag.Title = "Chi tiết hợp đồng";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon white edit"></i><span class="break"></span>Thông tin hợp đồng</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <form class="form-horizontal">
                <fieldset>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Tên đối tác: </p>
                        <p class="control-label-custom" for="focusedInput"><a class="link_custom" href="@Url.Action("Details", "ManagePartner", new { @id = Model.PARTNERID})">@Html.DisplayFor(model => model.PARTNER_INFO_SELLSIDE.NAME_PARTNER)</a></p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Tên sản phẩm: </p>
                        <p class="control-label-custom" for="focusedInput"><a class="link_custom" href="@Url.Action("Details", "ManagePartner", new { @id = Model.PRODUCTS.NAME })">@Html.DisplayFor(model => model.PRODUCTS.NAME)</a></p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Số lượng tồn kho tối thiểu: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.MININVENTORY)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Số lượng cung cấp tối thiểu: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.MINPROVIDE)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Thời gian giao hàng: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.DELAYTIME)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Thời gian hợp tác: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.COOPTIME)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Thời gian chuyển tiền: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.BILLTIME)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Ngày bắt đầu: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.STARTDAY)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Ngày kết thúc: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.ENDDAY)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Trạng thái hợp đồng: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.ACTIVE)</p>
                    </div>
                </fieldset>
            </form>

        </div>
    </div><!--/span-->

</div><!--/row-->

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon white edit"></i><span class="break"></span>Thông tin của đối tác</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <form class="form-horizontal">
                <fieldset>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Mã hợp đồng : </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.ORDER_ID_PARTNER)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Mã sản phẩm: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.PRODUC_ID_PARTNER)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Tên sản phẩm: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.PRODUCT_NAME_PARTNER)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Số lượng tồn kho: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.PRODUCT_QUANTITY_PARTNER)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Trạng thái: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.STATE)</p>
                    </div>
                </fieldset>
            </form>

        </div>
    </div><!--/span-->

</div><!--/row-->

<div class="form-actions">
    <button type="submit" class="btn btn-primary" onclick="window.location.href='@Url.Action("Edit", "B2BSellSide", new { id = Model.ID })'">Edit</button>
    <button class="btn" onclick="window.location.href='@Url.Action("returnURL", "AdminHome", new { returnURL = ViewBag.ReturnUrl })'">Back</button>
</div>

ec-th2012-c/ec-th2012-c/Views/B2BSellSide/getAllListBill.cshtml
@model IEnumerable<ec_th2012_c.Models.BILL2B_SELLSIDE>
@{
    ViewBag.Title = "getAllListBill";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon white user"></i><span class="break"></span>Danh sách đơn giao hàng</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        <th class="center_custom">Tên đối tác</th>
                        <th class="center_custom">Tên sản phẩm</th>
                        <th class="center_custom">Ngày gửi</th>
                        <th class="center_custom">Ngày đến</th>
                        <th class="center_custom">Số lượng</th>
                        <th class="center_custom">Trạng thái</th>

                        <th class="center_custom">Xác nhận</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        foreach (var item in Model)
                        {

                            <tr>
                                <td class="center_custom"><a class="link_custom"  href="@Url.Action("Details", "ManagePartnerSellSide", new { @id = item.CONTRACT_SELLSIDE.PARTNERID})">@item.CONTRACT_SELLSIDE.PARTNER_INFO_SELLSIDE.NAME_PARTNER</a></td>
                                <td class="center_custom"><a class="link_custom" href="@Url.Action("DetailProduct", "Product", new { @id = item.CONTRACT_SELLSIDE.PRODUCTID })">@item.CONTRACT_SELLSIDE.PRODUCTS.NAME</a></td>
                                <td class="center_custom">@item.DATECREATE</td>
                                <td class="center_custom">@item.DATERECEIVED</td>
                                <td class="center_custom">@item.QUANLITY</td>

                                @if (item.STATE == "đang giao hàng")
                                {
                                    <td class="center_custom"><span class="label label-warning">@item.STATE</span></td>
                                    <td class="center_custom">

                                        <a class="btn btn-success" href="@Url.Action("shippingOkAllList", "B2BSellSide", new { idBill = item.ID })">
                                            <i class="halflings-icon ok white"></i>
                                        </a>

                                    </td>
                                }
                                else
                                {
                                    <td class="center_custom"><span class="label label-success">@item.STATE</span></td>
                                    <td></td>
                                }





                            </tr>
                        }
                    }







                </tbody>
            </table>
        </div>
    </div><!--/span-->
</div>

ec-th2012-c/ec-th2012-c/Views/B2BSellSide/listBill.cshtml
@model IEnumerable<ec_th2012_c.Models.BILL2B_SELLSIDE>
@{
    ViewBag.Title = "Danh sách đơn hàng";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon white user"></i><span class="break"></span>Danh sách đơn giao hàng</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        <th class="center_custom">Ngày gửi</th>
                        <th class="center_custom">Ngày đến</th>
                        <th class="center_custom">Số lượng</th>
                        <th class="center_custom">Trạng thái</th>

                        <th class="center_custom">Xác nhận</th>
                    </tr>
                </thead>
                <tbody>
                   @{
                       foreach (var item in Model)
                       {

                        <tr>
                            <td class="center_custom">@item.DATECREATE</td>
                            <td class="center_custom">@item.DATERECEIVED</td>
                            <td class="center_custom">@item.QUANLITY</td>

                            @if (item.STATE == "đang giao hàng")
                            {
                            <td class="center_custom"><span class="label label-warning">@item.STATE</span></td>
                            <td class="center_custom">

                                <a class="btn btn-success" href="@Url.Action("shippingOk", "B2BSellSide", new { idContract = item.CONTRACTID, idBill = item.ID})">
                                    <i class="halflings-icon ok white"></i>
                                </a>

                            </td>
                            }
                            else
                            {
                            <td class="center_custom"><span class="label label-success">@item.STATE</span></td>
                                <td></td>
                            }





                        </tr>
                       }
                       }







                </tbody>
            </table>
        </div>
    </div><!--/span-->
</div>

<div class="form-actions">

    <button class="btn btn-primary" onclick="window.location.href='@Url.Action("returnURL", "AdminHome", new { returnURL = ViewBag.ReturnUrl })'">Back</button>
</div>