ec-th2012-c/ec-th2012-c/Controllers/ManagePartnerSellSideController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ec_th2012_c.DAO;
using System.Net;
using ec_th2012_c.Models;

namespace ec_th2012_c.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ManagePartnerSellSideController : Controller
    {
        private PartnerSellSideDAO dbPartner = new PartnerSellSideDAO();
        private ContractDAO dbContract = new ContractDAO();

        [HttpGet]
        // GET: ManagePartner
        public ActionResult Index()
        {
            var model = dbPartner.getListParter();
            return View("Index", model);
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = dbPartner.getDetailPartner(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            ViewBag.ReturnUrl = System.Web.HttpContext.Current.Request.UrlReferrer;
            return View("Details", model);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = dbPartner.getDetailPartner(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            ViewBag.ReturnUrl = System.Web.HttpContext.Current.Request.UrlReferrer;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PARTNER_INFO_SELLSIDE model)
        {
            if (ModelState.IsValid)
            {
                dbPartner.editPartner(model);

                return RedirectToAction("Details/" + model.ID);
            }

            return View(model);
        }

        public ActionResult Delete(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var cONTRACT_SELLSIDE = dbPartner.getDetailPartner(id);
            if (cONTRACT_SELLSIDE == null)
            {
                return HttpNotFound();
            }
            dbPartner.deletePartnerSellSide(id);
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {

            ViewBag.ReturnUrl = System.Web.HttpContext.Current.Request.UrlReferrer;
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PARTNER_INFO_SELLSIDE model)
        {
            
                dbPartner.createPartnerSellSide(model);

                return RedirectToAction("Index");
            
          

        }

        [HttpGet]
        public ActionResult Contracts(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var cONTRACT_SELLSIDE = dbPartner.getDetailPartner(id);
            if (cONTRACT_SELLSIDE == null)
            {
                return HttpNotFound();
            }
            var model = dbContract.getContractByPartner(id);
            
            return View("../B2BSellSide/Index", model);
        }
    }
}

ec-th2012-c/ec-th2012-c/Views/ManagePartnerSellSide/Create.cshtml
@model ec_th2012_c.Models.PARTNER_INFO_SELLSIDE
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm())
{
    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="halflings-icon white edit"></i><span class="break"></span>Thêm đối tác mua hàng</h2>
                <div class="box-icon">
                    <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                    <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                    <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
                </div>
            </div>
            <div class="box-content">

                @Html.AntiForgeryToken()
                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)
                    <fieldset>


                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Tên đối tác</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.NAME_PARTNER, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NAME_PARTNER, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Mô tả</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.DESCRIPTION, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DESCRIPTION, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Website</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.WEBSITE, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.WEBSITE, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Username</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.USERNAME, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.USERNAME, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Password</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.PASSWORD, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PASSWORD, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Link request token</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.LINK_REQUESTTOEKN, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.LINK_REQUESTTOEKN, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Link authenticate</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.LINK_AUTHENTICATE, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.LINK_AUTHENTICATE, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Link accesstoken</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.LINK_ACCESSTOKEN, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.LINK_ACCESSTOKEN, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Link orders</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.LINK_ORDERS, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.LINK_ORDERS, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Link shipping</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.LINK_SHIPPING, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.LINK_SHIPPING, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Consumer Key</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.CONSUMER_KEY, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.CONSUMER_KEY, "", new { @class = "text-danger" })
                            </div>
                        </div>




                    </fieldset>


                </div>

            </div>
        </div><!--/span-->

    </div><!--/row-->





    <div class="form-actions">
        <button type="submit" class="btn btn-primary">Create</button>
        <button class="btn" onclick="window.location.href='@Url.Action("returnURL", "AdminHome", new { returnURL = ViewBag.ReturnUrl })'">Cancel</button>
    </div>
}

ec-th2012-c/ec-th2012-c/Views/ManagePartnerSellSide/Details.cshtml
@model ec_th2012_c.Models.PARTNER_INFO_SELLSIDE

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon white edit"></i><span class="break"></span>Thông tin đối tác</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <form class="form-horizontal">
                <fieldset>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Tên đối tác: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.NAME_PARTNER)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Mô tả: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.DESCRIPTION)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Website: </p>
                        <p class="control-label-custom" for="focusedInput"><a href="@Html.DisplayFor(model => model.WEBSITE)" class="link_custom" target="_blank">@Html.DisplayFor(model => model.WEBSITE)</a></p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Username: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.USERNAME)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Password: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.PASSWORD)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Link request token: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.LINK_REQUESTTOEKN)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Link authenticate: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.LINK_AUTHENTICATE)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Link accesstoken: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.LINK_ACCESSTOKEN)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Link orders: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.LINK_ORDERS)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Link Shipping: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.LINK_SHIPPING)</p>
                    </div>
                    <div class="control-group">
                        <p class="control-label" for="focusedInput">Comsumer Key: </p>
                        <p class="control-label-custom" for="focusedInput">@Html.DisplayFor(model => model.CONSUMER_KEY)</p>
                    </div>
                </fieldset>
            </form>

        </div>
    </div><!--/span-->

</div><!--/row-->



<div class="form-actions">
    <button type="submit" class="btn btn-primary" onclick="window.location.href='@Url.Action("Edit", "ManagePartnerSellSide", new { id = Model.ID })'">Edit</button>
    <button class="btn" onclick="window.location.href='@Url.Action("returnURL", "AdminHome", new { returnURL = ViewBag.ReturnUrl })'">Back</button>
</div>

ec-th2012-c/ec-th2012-c/Views/ManagePartnerSellSide/Edit.cshtml
@model ec_th2012_c.Models.PARTNER_INFO_SELLSIDE
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm())
{
    <div class="row-fluid sortable">
        <div class="box span12">
            <div class="box-header" data-original-title>
                <h2><i class="halflings-icon white edit"></i><span class="break"></span>Chỉnh sửa thông tin đối tác mua hàng</h2>
                <div class="box-icon">
                    <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                    <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                    <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
                </div>
            </div>
            <div class="box-content">

                @Html.AntiForgeryToken()
                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)
                    <fieldset>


                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Tên đối tác</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.NAME_PARTNER, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NAME_PARTNER, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Mô tả</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.DESCRIPTION, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DESCRIPTION, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Website</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.WEBSITE, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.WEBSITE, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Username</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.USERNAME, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.USERNAME, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Password</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.PASSWORD, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PASSWORD, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Link request token</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.LINK_REQUESTTOEKN, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.LINK_REQUESTTOEKN, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Link authenticate</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.LINK_AUTHENTICATE, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.LINK_AUTHENTICATE, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Link accesstoken</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.LINK_ACCESSTOKEN, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.LINK_ACCESSTOKEN, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Link orders</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.LINK_ORDERS, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.LINK_ORDERS, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Link shipping</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.LINK_SHIPPING, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.LINK_SHIPPING, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="control-group success">
                            <label class="control-label" style="color:black !important" for="focusedInput">Consumer Key</label>
                            <div class="controls">
                                @Html.EditorFor(model => model.CONSUMER_KEY, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.CONSUMER_KEY, "", new { @class = "text-danger" })
                            </div>
                        </div>




                    </fieldset>


                </div>

            </div>
        </div><!--/span-->

    </div><!--/row-->


   

  
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">Save Change</button>
        <button class="btn" onclick="window.location.href='@Url.Action("returnURL", "AdminHome", new { returnURL = ViewBag.ReturnUrl })'">Cancel</button>
    </div>
}

ec-th2012-c/ec-th2012-c/Views/ManagePartnerSellSide/Index.cshtml
@model IEnumerable<ec_th2012_c.Models.PARTNER_INFO_SELLSIDE>

@{
    ViewBag.Title = "Quản lý đối tác";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="header_create">
    <a class="btn btn-success" href="@Url.Action("Create", "ManagePartnerSellSide")">
        <i class="halflings-icon edit white"></i>
    </a>

</div>

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon white user"></i><span class="break"></span>Danh sách đối tác mua hàng</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        <th class="center_custom">Tên đối tác</th>
                        <th class="center_custom">Mô tả</th>
                        <th class="center_custom">Email</th>
                        <th class="center_custom">Web</th>  
                        <th class="center_custom">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {

                        <tr>
                            <td>@Html.DisplayFor(m => item.NAME_PARTNER)</td>
                            <td>@Html.DisplayFor(m => item.DESCRIPTION)</td>
                            <td class="center_custom">@Html.DisplayFor(m => item.EMAIL)</td>
                            <td class="center_custom"><a class="link_custom" href="@Html.DisplayFor(m => item.WEBSITE)" target="_blank">@Html.DisplayFor(m => item.WEBSITE)</a></td>
                           
                           

                            <td class="center_custom">

                                <a class="btn btn-success" href="@Url.Action("Details", "ManagePartnerSellSide", new { id = item.ID })">
                                    <i class="halflings-icon white zoom-in"></i>
                                </a>
                                <a class="btn btn-info" href="@Url.Action("Contracts", "ManagePartnerSellSide", new { id = item.ID })">
                                    <i class=" halflings-icon list white"></i>
                                </a>
                                <a class="btn btn-danger" href="@Url.Action("Delete", "ManagePartnerSellSide", new { id = item.ID })" onclick="return confirm('Do you want delete this partner?')">
                                    <i class="halflings-icon white trash"></i>
                                </a>
                            </td>
                        </tr>



                    }


                </tbody>
            </table>
        </div>
    </div><!--/span-->
</div>